[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=46.0.5",
    "curl-cffi>=0.13.0",
    "flask-cors>=6.0.2",
    "pmxt>=2.10.0",
    "psycopg2-binary>=2.9.11",
    "py-clob-client>=0.28.0",
    "pysocks>=1.7.1",
    "requests[socks]>=2.32.5",
    "web3>=7.14.0",
]
